nohup python -u rollout_lazy.py --index 0 > lazy_log/0.log 2>&1 &
nohup python -u rollout_lazy.py --index 1 > lazy_log/1.log 2>&1 &
nohup python -u rollout_lazy.py --index 2 > lazy_log/2.log 2>&1 &
nohup python -u rollout_lazy.py --index 3 > lazy_log/3.log 2>&1 &
nohup python -u rollout_lazy.py --index 4 > lazy_log/4.log 2>&1 &
nohup python -u rollout_lazy.py --index 5 > lazy_log/5.log 2>&1 &
nohup python -u rollout_lazy.py --index 6 > lazy_log/6.log 2>&1 &
nohup python -u rollout_lazy.py --index 7 > lazy_log/7.log 2>&1 &
nohup python -u rollout_lazy.py --index 8 > lazy_log/8.log 2>&1 &
nohup python -u rollout_lazy.py --index 9 > lazy_log/9.log 2>&1 &